import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // 기존 색상 보존
        ink: "#17211c",
        mist: "#eef5f0",
        moss: "#5f7f68",
        fern: "#2f6f4f",
        clay: "#c36f4a",
        lemon: "#f3c95f",

        // 시안(focusflow_ai)의 M3 테마 색상 추가
        "error-container": "#ffdad6",
        "outline-variant": "#c3c5d9",
        "inverse-surface": "#283044",
        "secondary-fixed-dim": "#abd600",
        "on-surface-variant": "#434656",
        secondary: "#506600",
        "secondary-container": "#c1f100",
        "surface-container": "#eaedff",
        "on-primary-container": "#e3e6ff",
        "surface-container-lowest": "#ffffff",
        tertiary: "#972500",
        "on-secondary-container": "#546b00",
        "on-background": "#131b2e",
        "secondary-fixed": "#c3f400",
        "tertiary-fixed": "#ffdbd1",
        "inverse-on-surface": "#eef0ff",
        surface: "#faf8ff",
        "on-tertiary-fixed-variant": "#872100",
        "surface-tint": "#004dea",
        error: "#ba1a1a",
        "surface-container-low": "#f2f3ff",
        "on-primary-fixed-variant": "#0039b3",
        background: "#faf8ff",
        "on-secondary-fixed-variant": "#3c4d00",
        "primary-container": "#0055ff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001551",
        primary: "#0041c8",
        "surface-dim": "#d2d9f4",
        "on-secondary": "#ffffff",
        "on-surface": "#131b2e",
        "tertiary-fixed-dim": "#ffb5a0",
        "tertiary-container": "#c13301",
        "on-primary": "#ffffff",
        "surface-variant": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "primary-fixed-dim": "#b6c4ff",
        "surface-bright": "#faf8ff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed": "#3b0900",
        "inverse-primary": "#b6c4ff",
        "on-tertiary": "#ffffff",
        outline: "#737688",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-container": "#ffe1d9",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#161e00",
      },
      boxShadow: {
        soft: "0 18px 60px rgba(31, 46, 38, 0.12)",
      },
      spacing: {
        "margin-desktop": "64px",
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        code: ["Geist Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        code: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
